services:
  consumer:
    build:
      context: .
      dockerfile: Dockerfile.consumer
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9093
    depends_on:
      - kafka
    networks:
      - app-network

  producer:
    build:
      context: .
      dockerfile: Dockerfile.producer
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9093
    depends_on:
      - kafka
    networks:
      - app-network

  node:
    build:
      context: ./node
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - app-network

  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9093
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - app-network

  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_LISTENER_PORT: 2181
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
    attachable: true
